### ISSUE TITLE
Collaborator icons should increment horizontally

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#100]
Current behavior:

![screen shot 2019-02-11 at 2 57 29 pm](https://user-images.githubusercontent.com/11339965/52599536-bfde9a00-2e0d-11e9-976f-208b3cfc77db.png)

Once we start getting 10+ contributors on each asset, this is going to take up a lot of real estate on the page. I'd recommend adding contributors horizontally instead of vertically.

**Comment by pzupan** [comment]
Pull Request #102
