### ISSUE TITLE
New UI designs and recommendations

### ISSUE THREAD

**Issue by Brettwag** [sensu/bonsai-asset-index#101]
We have a number of [UI recommendations](https://www.dropbox.com/sh/pop1a7j0kif08ka/AAC-4tulWrj879QGY4zNmxqxa?dl=0) to clean up with existing frontend. 

@calebhailey 

**Global**
Overall we focused on type, color and spacing consistency. To save time, we didn’t go searching for every icon but allowed for space there. Also, we based the grid off of the columns we saw in the live site, so expecting a few things may shift around but hoping this provides enough clarity around spacing.

**Home**
Really similar to what currently exists, added in a description text block and updated the search area. Also, the addition of a CTA section at the bottom which can be used elsewhere.

**Assets**
Same layout but cleaned up the type size and spacing a bit. Open to suggestions on how items may change in proximity to each other, but this felt logical and easy to read, especially in regards to the tabs at the top and the right-hand sidebar.

**Collaborator**
Didn’t change much here, but offered suggestions on how to give that page a bit more depth by adjusting the pale colors.

**Comment by pzupan** [comment]
Pull Request #125
