### ISSUE TITLE
Enterprise assets not found

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#103]
This might not be a Bonsai issue, but selecting the links on this page https://bonsai.sensu.io/assets?tiers%5B%5D=4 results in `The page you were looking for does not exist`. However, the original links still work.

Example:

- Working: https://bonsai.sensu.io/assets/portertech/sensu-servicenow-handler
- Not working: https://bonsai.sensu.io/assets/sensu/sensu-servicenow-handler

**Comment by pzupan** [comment]
This is related to issue #90
