### ISSUE TITLE
Markdown rendering issue

### ISSUE THREAD

**Issue by ccressent** [sensu/bonsai-asset-index#106]
On the [bonsai page for `sensu-influxdb-handler`](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler), down in the "Usage Examples" section, the markdown is not rendered properly; see [the markdown rendered on github](https://github.com/sensu/sensu-influxdb-handler#usage-examples) for comparison.

It looks like the \``` right after "Help:" is not taken into account.

**Comment by mbiang** [comment]
Thanks @ccressent - we'll take a look.   CC @pzupan

**Comment by pzupan** [comment]
Pull request #110
