### ISSUE TITLE
Search is "inflexible"

### ISSUE THREAD

**Issue by ccressent** [sensu/bonsai-asset-index#108]
Search terms in the search bar have to be pretty precise to find results. Here is an example of what I mean:
- [Search for "influx"](https://bonsai.sensu.io/assets?utf8=%E2%9C%93&q=influx&supported_platform_id=)
0 results
- [Search for "influxdb"](https://bonsai.sensu.io/assets?utf8=%E2%9C%93&q=influxdb&supported_platform_id=)
1 result; the expected `sensu-influxdb-handler`

In both case I'm expecting to come across `sensu-influxdb-handler` in the results. In fact, I would expect a query such as `TERM1 TERM2` to be handled as a regular expression similar to `.*TERM1.*TERM2.*`, where the terms can appear in any order.

**Comment by pzupan** [comment]
Pull Request #112
