### ISSUE TITLE
Oversized image in asset list

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#109]
On this page https://bonsai.sensu.io/assets, one of the contributor icons appears oversized.

![screen shot 2019-02-26 at 9 14 54 am](https://user-images.githubusercontent.com/11339965/53432416-529f3d00-39a7-11e9-8187-987975042bf6.png)

**Comment by pzupan** [comment]
Pull request #111

**Comment by apaskulin** [comment]
@pzupan This seems to have created some oddly sized images on the main Bonsai page: Profile pic too large, thumbnails too narrow.

![screen shot 2019-02-27 at 11 12 02 am](https://user-images.githubusercontent.com/11339965/53516301-d4af6480-3a80-11e9-935c-4240885cb73d.png)

**Comment by apaskulin** [comment]
Everything looks correct now. Thanks!

**Comment by apaskulin** [comment]
I'm seeing this original issue again.
