### ISSUE TITLE
Avatars on homepage are stretched

### ISSUE THREAD

**Issue by amdprophet** [sensu/bonsai-asset-index#114]
When visiting the homepage, the avatars appear stretched. It looks as if the width isn't being applied correctly or the avatars have too much height.

![screen shot 2019-02-27 at 11 32 12 am](https://user-images.githubusercontent.com/120659/53517483-91a2c080-3a83-11e9-8a7e-57643f420839.png)

**Comment by pzupan** [comment]
The change made in pull #111 incorporated some latent image sizes in legacy code.  Not pretty.  Hopefully I've found and fixed them all.
