### ISSUE TITLE
Copy updates: homepage

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#119]
Copy changes for http://bonsai.sensu.io homepage

- Change GitHub sign in link to use sentence case: "Sign in with GitHub"
- Change the search bar placeholder text ("Add-ons, tags, authors...") to "Assets, tags, authors…"
- Change the intro text beneath search bar ("Extend Sensu using add-ons and share your own with the community") to "Welcome to Bonsai, the Sensu asset index. Discover and [share](https://bonsai.sensu.io/new) assets for all your monitoring needs."
- Change three main columns from "New & updated", "Noteworthy", and "Categories" to "Recently updated", "Featured", and "Tags"
- Replace the "Share your creations!" section at the bottom of the page with the following content:

#### Learn about Sensu assets

**What is an asset?**
Assets are shareable, reusable packages that make it easy to deploy Sensu plugins. You can use assets to provide the plugins, libraries, and runtimes you need to automate your monitoring workflows. Log in with your GitHub account to [share your assets](https://bonsai.sensu.io/new) on Bonsai.

**Tiers**
- [Community](https://bonsai.sensu.io/assets?tiers%5B%5D=1) - Open-source assets shared by the Sensu Community. Collaborate, share, and star your favorites with Bonsai.
- [Supported](https://bonsai.sensu.io/assets?tiers%5B%5D=2) - Open-source assets supported by Sensu Inc., including supported [Slack](https://bonsai.sensu.io/assets/sensu/sensu-slack-handler), [PagerDuty](https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler), and [InfluxDB](https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler) handlers.
- [Enterprise](https://bonsai.sensu.io/assets?tiers%5B%5D=4) - Hosted assets unlocked with a Sensu enterprise license. See the [Sensu docs](https://docs.sensu.io/sensu-go/latest/getting-started/enterprise) for more information about managing your Sensu license.

**Resources**

- [Deploying Sensu plugins with Bonsai](https://docs.sensu.io/sensu-go/latest/guides/install-check-executables-with-assets)
- [Sharing an asset on Bonsai](https://docs.sensu.io/sensu-go/latest/reference/assets#sharing-an-asset-on-bonsai)

**Comment by pzupan** [comment]
Pull Request #125
