### ISSUE TITLE
Copy updates: New asset page

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#120]
Copy updates for https://bonsai.sensu.io/new

Replace the content in the right sidebar ("ADDING AN ASSET...") with the following content:

### How to share assets on Bonsai

Thank you for sharing your asset with the Sensu Community! Here’s how it works: Bonsai pulls project details and release information from GitHub to populate an asset page. To share an asset on Bonsai, the asset should be in a public GitHub repository that includes:

- [GitHub release](https://help.github.com/articles/creating-releases/) tags
- bonsai.yml [configuration file](https://docs.sensu.io/sensu-go/latest/reference/assets#sharing-an-asset-on-bonsai) with the project description, platforms, asset filenames, and checksums
- A helpful README following the [asset README template](https://github.com/sensu/sensu-go-plugin)
- A license and code of conduct (We ❤️ the [MIT license](https://github.com/sensu/sensu-go/blob/master/LICENSE) and welcome you to borrow from our [community code of conduct](https://sensu.io/conduct/).)

Bonsai automatically keeps in sync with your GitHub releases. For more information about creating and sharing assets, see the [Sensu docs](https://docs.sensu.io/sensu-go/latest/reference/assets) and the [Sensu Go plugin template](https://github.com/sensu/sensu-go-plugin).

**Comment by pzupan** [comment]
Pull Request #125
