### ISSUE TITLE
Copy updates: Site metadata

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#121]
Updates to site metadata

- Change title from "Assets Directory - Bonsai Asset Index" to "Sensu assets | Bonsai asset index"
- Change description from "Browse and search Sensu assets. Learn how to use and create assets for configuring your infrastructure." to "Welcome to Bonsai, the Sensu asset index. Bonsai offers popular integrations like the Sensu Slack, InfluxDB, and PagerDuty handlers. Discover, download, and share assets for all your monitoring needs."

**Comment by pzupan** [comment]
Pull Request #125
