### ISSUE TITLE
Copy updates: Enterprise asset download prompt

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#123]
Copy updates for the enterprise asset download prompt.

![Screen Shot 2019-03-08 at 2 21 22 PM](https://user-images.githubusercontent.com/11339965/54059529-5e141480-41ae-11e9-9c68-3c8c29c5e820.png)

- Change "This asset is intended for enterprise license holders only." to "This asset is enterprise only and requires an [enterprise license](https://docs.sensu.io/sensu-go/latest/getting-started/enterprise/). By clicking download, you agree to the [Sensu terms and conditions](https://sensu.io/sensu-terms-and-conditions) and [license agreement](https://sensu.io/sensu-license)."
- Change "I acknowledge that this asset is only for enterprise license holders." to "I am an enterprise license holder."

**Comment by pzupan** [comment]
Pull Request #125
