### ISSUE TITLE
Asset in Bonsai did not have the latest release

### ISSUE THREAD

**Issue by rgeniesse** [sensu/bonsai-asset-index#127]
The Sensu Go email handler is on version `0.1.0`:

https://github.com/sensu/sensu-email-handler/releases

But in Bonsai, the latest was showing as `0.0.2`

Running recompile releases fixed it. Is there any information on the backend that can be provided on why this may have happened?

If not, I can close and we can revisit if the issue continues to happen on future releases or other assets.

Thanks!

**Comment by pzupan** [comment]
Sorry.  I reset it while testing and forgot to change it back.
