### ISSUE TITLE
Please remove the "welcome" banner

### ISSUE THREAD

**Issue by bananabele** [sensu/bonsai-asset-index#128]
Please remove the blue banner that appears when you first visit bonsai.sensu.io. Thanks! 
<img width="1389" alt="Screen Shot 2019-03-14 at 1 20 37 PM" src="https://user-images.githubusercontent.com/38439765/54381508-fcdfbb80-465b-11e9-8369-6d6105b16d8f.png">

**Comment by pzupan** [comment]
Pull Request #131
