### ISSUE TITLE
Please update featured assets

### ISSUE THREAD

**Issue by bananabele** [sensu/bonsai-asset-index#130]
Update the featured assets on the homepage to:
ServiceNow - https://bonsai.sensu.io/assets/sensu/sensu-servicenow-handler
PagerDuty - https://bonsai.sensu.io/assets/sensu/sensu-pagerduty-handler
Prometheus Collector - https://bonsai.sensu.io/assets/sensu/sensu-prometheus-collector

**Comment by pzupan** [comment]
Featured is currently not a fixed list of assets.  It is currently displaying the most downloaded assets.

Extension.
      includes(:extension_versions).
      where.not(owner: nil).
      ordered_by('most_downloaded').
      limit(5)

**Comment by bananabele** [comment]
Got it - in that case, could we please update that column header to "Most downloaded" (and change the column next to it to sentence case: "Recently updated" )?
Thank you!

**Comment by pzupan** [comment]
Pull Request #131
