### ISSUE TITLE
Display of asset URLs and checksums can cause confusion

### ISSUE THREAD

**Issue by rgeniesse** [sensu/bonsai-asset-index#132]
The current display of the asset URLs and checksums can cause confusion on which link pairs with which checksum. I illustrate this in the below screen shot:

<img width="448" alt="Screen Shot 2019-03-18 at 1 46 58 PM" src="https://user-images.githubusercontent.com/19964713/54566327-c7094280-498d-11e9-811f-7436373e3462.png">

As a user, if I begin at the top or the bottom of the asset list, I can see the pairings properly. But if I am looking for a build for an architecture in the middle, see the fourth red box 4, it isn't apparent what they pairs are. This can lead to mismatched download links and check sums.

Possible solution: Add a line to break it up or even a background box of a different color. I am not a frontend person, so not sure of the technical terms there for web dev.

**Comment by mbiang** [comment]
@rgeniesse I like the idea of dividing by a horizontal light grey border to provide some visual differentiation between the items.  CC @pzupan

**Comment by pzupan** [comment]
Pull request #138
