### ISSUE TITLE
Copy update: asset name field

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#133]
On https://bonsai.sensu.io/new, change "Please use title case for the name, e.g. My Gift to the Community." to “Asset names can contain lowercase letters, numbers, underscores, and dashes (for example: sensu-email-handler).”

Ideally, Bonsai would validate the input in the name field to enforce these constraints, but a copy update is a great start.

**Comment by pzupan** [comment]
Pull request #140
