### ISSUE TITLE
Link styling

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#134]
Links on the Bonsai homepage should be recognizable as links.

For example:

![Screen Shot 2019-03-20 at 9 51 53 AM](https://user-images.githubusercontent.com/11339965/54703360-e3c08a00-4af5-11e9-9fc5-01a6c8117587.png)

^ "share" is a link

![Screen Shot 2019-03-20 at 9 52 01 AM](https://user-images.githubusercontent.com/11339965/54703401-f2a73c80-4af5-11e9-8bad-533ded98bf9b.png)

^ "Community", "Supported", "Sensu docs", etc. are links

**Comment by pzupan** [comment]
Pull request #137
