### ISSUE TITLE
Github extended symver tag strings being stripped

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#136]
tag strings of the form "1.2.3-rc.1+build.1"  and "1.2.3+build.1" should be legal symver but Bonsai is unable to process github tags with prerelease (-) and/or metadata (+) suffixes.

As per discussion, it appears that Bonsai is stripping information past the patch level

I'll setup a repository with non functional example tags with prerelease and metadata sections for testing and add them in as an additional comment.

**Comment by pzupan** [comment]
Pull Request #139
