### ISSUE TITLE
Asset description - Truncate after 3rd line of description text. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/bonsai-asset-index#141]
Right now, descriptions are displayed in full regardless of their length. Let's wrap after the 3rd line of the description text and put ellipses if there is more as an indicator. 

Attached is a screenshot of the current behavior.

**Comment by annaplotkin** [comment]
![Screen Shot 2019-03-21 at 2 03 58 PM](https://user-images.githubusercontent.com/41910800/54785325-2dd36980-4be3-11e9-8082-bad2107b6322.png)

**Comment by pzupan** [comment]
Pull request #142
