### ISSUE TITLE
README.md tables are not rendered properly

### ISSUE THREAD

**Issue by nixwiz** [sensu/bonsai-asset-index#144]
I have a couple of handler assets that I added to bonsai.  Both of them make use of Markdown tables in README.md.  These tables are not being rendered properly on the bonsai site.

[Example asset](https://bonsai.sensu.io/assets/nixwiz/sensu-go-flowdock-handler)

Screenshot:
<img width="857" alt="Screen Shot 2019-03-29 at 8 41 27 PM" src="https://user-images.githubusercontent.com/5530473/55270965-0d4e8380-5263-11e9-9d89-128649303cc7.png">

Confirmed to occur with Chrome and Safari.

**Comment by mbiang** [comment]
Thanks @nixwiz - we'll take a look!
