### ISSUE TITLE
Make it possible to set asset tags via API or via GItub release compile

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#154]
Not sure what the best approach here is, but it would be fantastic if I could twiddle the tag list from the bonsai.yml or via an API endpoint so I don't have to manually set tags in the web interface.

Tags are a little weird in that they are repository scoped, not asset version scoped.. making it hard for this to work from bonsai.yml, but perfect for an API endpoint that I can PUT.

**Comment by pzupan** [comment]
Pull Request #166
