### ISSUE TITLE
Allow asset deprecate to asset from different namespace 

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#155]
## Desired Behavior
I want to deprecate 
https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-disk-checks
and point people to 
https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-disk-checks

## Problem
The deprecate dialog doesn't expose or allow me to search by namespace.
I can search for and select 'sensu-plugins-disk-checks'  but that ends up just selecting the asset I'm trying to deprecate.... effectively pointing people who got to
https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-disk-checks
back to itself.

**Comment by pzupan** [comment]
Pull Request #158
