### ISSUE TITLE
Update deprecation warning message to show namespace/repo

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#159]
Small cleanup for deprecation warning.
Right now it only shows the repository name, in the message, it might be better to show
namespace/repo for clarity

Ex:
https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-chef
could read:
```
jspaleta/sensu-plugins-chef has been deprecated in favor of sensu-plugins/sensu-plugins-chef
```

**Comment by mbiang** [comment]
@jspaleta - this has been updated!
