### ISSUE TITLE
Include production asset suggestion in bonsai.yml

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#160]
I expect forks of upstream assets to appear in bonsai a lot under different namespaces.
It would be fantastic if the maintainers of that fork could give guidance to users to prefer the upstream version if its known to be more stable.

Expected workflow where this could help
1. fork upstream asset
2. make some changes that suit my environment or experimental changes.
3. list asset under my namespace.
4. use forked asset in my environment
5. other user sees my fork and tries to use it, gets bad experience.

If I had a way to explicitly suggest the upstream asset, and let bonsai UI put up a suggestion block (where the deprecation block shows up now) that would be fantastic.

##Strawman
two bonsai.yaml attributes
- sensu.bonsai.io.suggested_asset_url
-sensu.bonsai.io.suggested_message

If suggested_asset is set, bonsai will show a suggested block pointing people to the other asset
if the suggest_message attribute is set, bonsai ui will use that message string instead of the default.

**Comment by pzupan** [comment]
Requires #153
