### ISSUE TITLE
Allow versions to be skipped in latest version calculation

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#161]
### Problem Statement
When working on a pre-release version tag, I'd prefer to be able to instruct bonsai to skip this tag when making the decision as to what the latest version is, so that the pre-release version isn't the default in the pull down.

### Strawman 1
have a bonsai.yml attribute that will instruct bonsai to not allow this version to be pre-selected in the pull down.

```bonsai.sensu.io.allow_default  = true/false```
with default to true.

if set to true, the version is still available in the pull down, its just not pre-selected as the default in the pull down.

**Comment by mbiang** [comment]
@jspaleta - I wonder if this could be inferred from the version tags, specifically if assets have a semver pre-release version number:   https://semver.org/#spec-item-9

We could have the asset page determine the latest version based on version numbers that don't contain a pre-release tag.   It seems that would keep in line with the intention behind the pre-release tagging spec.

Alternately, we could support that metadata approach in the yml that you describe above.  Just wondering if you prefer an explicit or implicit approach.

**Comment by pzupan** [comment]
Requires #153

**Comment by mbiang** [comment]
Let's rely on the SEMVER approach.  If the asset contains a pre-release tag, it shouldn't be selected as the default release on the asset details page.
