### ISSUE TITLE
Allow for explictly setting the default version in the version pull-down

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#162]
## Problem statement

I want to explicitly set a default version for best user experience...even when new version is available. Especially true when major new version lands with breaking changes...until new version is tested well enough...might require a couple of patch releases before fully trusted for all users.  

### Strawman
allow for explict setting of default version in version dropdown, but i'm not sure how to make that work in the context of the bonsai.yml config.. because it would have to be repository scoped instead of release version scoped.else multiple versions could be asking to be default and that makes no sense.  If we wanted to implement that, it would be part of asset management UI and/or an API interaction. API interaction is great for CI/CD integration.

**Comment by mbiang** [comment]
@jspaleta 

If we did want to add this as a metadata setting in bonsai.yml, I think we could just have the highest release version that declares itself the default be the winner.   Alternately, a UI approach similar to deprecation or an asset api endpoint would work fine as well.

It seems like doing as much as we can in bonsai.yml is the preferred solution, but let me know what you think of the approach there.

**Comment by pzupan** [comment]
Requires #153

**Comment by mbiang** [comment]
We basically want a UI control to set a default asset version.   

- Under "Manage Asset", add an option to "Pin Default Release".
- This should open a dialog that allows you to select an asset version as the default.
- If the asset has a default release, that release should always be pre-selected in the asset drop down.
- If the asset has a default release, there should be an option under "Manage Asset" to unpin the release.
