### ISSUE TITLE
Hosted Release Assets don't match SHA and can't be extracted.

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#163]
**Expected Behavior**

- Downloaded release assets SHA hashes should match  the expected SHA has displayed under the asset on the sidebar.
- Downloaded release assets (in tar.gz format) should be able to be extracted using tar command line tools.

**Actual Behavior**
- Downloaded release assets don't always match their expected SHA hash.
- Extracting downloaded tar.gz archives results in "tar: Unrecognized archive format"

**Steps to Reproduce**

1. Open https://bonsai.sensu.io/assets/sensu/sensu-aggregate-check and select version 0.0.6
2. Download the https://bonsai.sensu.io/release_assets/sensu/sensu-aggregate-check/0.0.6/linux/amd64/asset_file release asset from the right sidebar
3. Run shasum -a 512 [path to downloaded asset].  The resulting hash will not match the hash displayed for this asset on the sidebar.
4. Run tar -zxvg [path to downloaded asset].  You will get the following error:  "tar: Unrecognized archive format"

Notes:  The original uploaded tar file contains release asset in question.  The release asset in the original tarball extracts successfully, and matches the expected sha hash.  The original uploaded tar file can be provided by @mbiang on request,

**Comment by demillir** [comment]
The issue is related to this commit: https://github.com/sensu/bonsai-asset-index/commit/88da14ee0132be652bdb32abf0bd5567162ce324

For the asset version in the above description, the encoding to UTF-8 replaces a bunch of characters with `_`.

**Comment by pzupan** [comment]
Issue #147 should fix this issue.
