### ISSUE TITLE
"v" prefix breaks sorting on extension version selector

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#180]
**Expected Behavior**

I expect version numbers with a "v" prefix and a valid Semver version number to be sorted similar to a Semver version number without the "v" prefix.  For example:  "v1.0.0" should appear before "1.0.1".

**Actual Behavior**

Version numbers with a "v" prefix are appearing higher in the sorting than version numbers without the "v" prefix.   See https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler/

<img width="1521" alt="Screen Shot 2019-07-09 at 3 22 57 PM" src="https://user-images.githubusercontent.com/155588/60920306-7def3e00-a25d-11e9-9790-89cd0b3e5969.png">

**Comment by pzupan** [comment]
Pull request #184
