### ISSUE TITLE
Encoding Error during Hosted Asset Processing

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#181]
The sensu-aggregate-check asset appears to be failing during active_storage analysis due to an encoding error encountered somewhere in the asset's meta data or build binaries.   The following stack track is occurring in the background jobs while trying to process this asset:

> 2019-07-09T20:14:57.236983+00:00 app[worker.1]: 4 TID-ov4gtnxok WARN: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
> 2019-07-09T20:14:57.237358+00:00 app[worker.1]: 4 TID-ov4gtnxok WARN: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:38:in `encode'
> 2019-07-09T20:14:57.237361+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:38:in `to_json'
> 2019-07-09T20:14:57.237362+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/core_ext/object/json.rb:38:in `to_json'
> 2019-07-09T20:14:57.237364+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:57:in `to_json'
> 2019-07-09T20:14:57.237365+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:224:in `generate'
> 2019-07-09T20:14:57.237367+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:224:in `generate'
> 2019-07-09T20:14:57.237368+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:102:in `stringify'
> 2019-07-09T20:14:57.237370+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:35:in `encode'
> 2019-07-09T20:14:57.237371+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/json/encoding.rb:22:in `encode'
> 2019-07-09T20:14:57.237372+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/coders/json.rb:7:in `dump'
> 2019-07-09T20:14:57.237374+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/store.rb:192:in `dump'
> 2019-07-09T20:14:57.237375+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/type/serialized.rb:29:in `serialize'
> 2019-07-09T20:14:57.237377+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/type/helpers/mutable.rb:8:in `cast'
> 2019-07-09T20:14:57.237378+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute.rb:175:in `type_cast'
> 2019-07-09T20:14:57.237380+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute.rb:42:in `value'
> 2019-07-09T20:14:57.237381+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute.rb:156:in `changed_from_assignment?'
> 2019-07-09T20:14:57.237383+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute.rb:59:in `changed?'
> 2019-07-09T20:14:57.237384+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute_mutation_tracker.rb:49:in `changed?'
> 2019-07-09T20:14:57.237386+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute_mutation_tracker.rb:43:in `block in any_changes?'
> 2019-07-09T20:14:57.237387+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute_mutation_tracker.rb:43:in `any?'
> 2019-07-09T20:14:57.237389+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2/lib/active_model/attribute_mutation_tracker.rb:43:in `any_changes?'
> 2019-07-09T20:14:57.237390+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/attribute_methods/dirty.rb:104:in `has_changes_to_save?'
> 2019-07-09T20:14:57.237392+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/timestamp.rb:118:in `should_record_timestamps?'
> 2019-07-09T20:14:57.237393+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/timestamp.rb:106:in `_update_record'
> 2019-07-09T20:14:57.237395+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:703:in `create_or_update'
> 2019-07-09T20:14:57.237396+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `block in create_or_update'
> 2019-07-09T20:14:57.237397+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:132:in `run_callbacks'
> 2019-07-09T20:14:57.237399+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/airbrake-8.1.4/lib/airbrake/rails/active_record.rb:20:in `run_callbacks'
> 2019-07-09T20:14:57.237400+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
> 2019-07-09T20:14:57.237401+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/callbacks.rb:342:in `create_or_update'
> 2019-07-09T20:14:57.237403+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:306:in `save!'
> 2019-07-09T20:14:57.237405+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/validations.rb:52:in `save!'
> 2019-07-09T20:14:57.237407+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `block in save!'
> 2019-07-09T20:14:57.237408+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
> 2019-07-09T20:14:57.237410+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:257:in `transaction'
> 2019-07-09T20:14:57.237411+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
> 2019-07-09T20:14:57.237416+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
> 2019-07-09T20:14:57.237417+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:315:in `save!'
> 2019-07-09T20:14:57.237419+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/suppressor.rb:48:in `save!'
> 2019-07-09T20:14:57.237420+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:439:in `block in update!'
> 2019-07-09T20:14:57.237422+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
> 2019-07-09T20:14:57.237423+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `block in transaction'
> 2019-07-09T20:14:57.237425+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
> 2019-07-09T20:14:57.237426+00:00 app[worker.1]: /app/vendor/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
> 2019-07-09T20:14:57.237428+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
> 2019-07-09T20:14:57.237429+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:259:in `transaction'
> 2019-07-09T20:14:57.237431+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:212:in `transaction'
> 2019-07-09T20:14:57.237432+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
> 2019-07-09T20:14:57.237434+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/persistence.rb:437:in `update!'
> 2019-07-09T20:14:57.237435+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.2/app/models/active_storage/blob/analyzable.rb:29:in `analyze'
> 2019-07-09T20:14:57.237437+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.2/app/jobs/active_storage/analyze_job.rb:6:in `perform'
> 2019-07-09T20:14:57.237439+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:39:in `block in perform_now'
> 2019-07-09T20:14:57.237440+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
> 2019-07-09T20:14:57.237441+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/i18n-1.5.3/lib/i18n.rb:284:in `with_locale'
> 2019-07-09T20:14:57.237443+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
> 2019-07-09T20:14:57.237445+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
> 2019-07-09T20:14:57.237446+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
> 2019-07-09T20:14:57.237448+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
> 2019-07-09T20:14:57.237449+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
> 2019-07-09T20:14:57.237451+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
> 2019-07-09T20:14:57.237452+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
> 2019-07-09T20:14:57.237454+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
> 2019-07-09T20:14:57.237455+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/logging.rb:46:in `block in tag_logger'
> 2019-07-09T20:14:57.237457+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
> 2019-07-09T20:14:57.237458+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
> 2019-07-09T20:14:57.237459+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
> 2019-07-09T20:14:57.237461+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/logging.rb:46:in `tag_logger'
> 2019-07-09T20:14:57.237462+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
> 2019-07-09T20:14:57.237464+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
> 2019-07-09T20:14:57.237465+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
> 2019-07-09T20:14:57.237466+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
> 2019-07-09T20:14:57.237470+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:38:in `perform_now'
> 2019-07-09T20:14:57.237471+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:24:in `block in execute'
> 2019-07-09T20:14:57.237473+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
> 2019-07-09T20:14:57.237474+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
> 2019-07-09T20:14:57.237475+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
> 2019-07-09T20:14:57.237477+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'
> 2019-07-09T20:14:57.237478+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:83:in `wrap'
> 2019-07-09T20:14:57.237479+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
> 2019-07-09T20:14:57.237481+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
> 2019-07-09T20:14:57.237482+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
> 2019-07-09T20:14:57.237483+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
> 2019-07-09T20:14:57.237485+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
> 2019-07-09T20:14:57.237486+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:22:in `execute'
> 2019-07-09T20:14:57.237487+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
> 2019-07-09T20:14:57.237489+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
> 2019-07-09T20:14:57.237490+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
> 2019-07-09T20:14:57.237492+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
> 2019-07-09T20:14:57.237493+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:133:in `invoke'
> 2019-07-09T20:14:57.237494+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:166:in `block in process'
> 2019-07-09T20:14:57.237496+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
> 2019-07-09T20:14:57.237497+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:108:in `local'
> 2019-07-09T20:14:57.237498+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
> 2019-07-09T20:14:57.237500+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:43:in `block in call'
> 2019-07-09T20:14:57.237501+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
> 2019-07-09T20:14:57.237502+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:73:in `block in wrap'
> 2019-07-09T20:14:57.237504+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:87:in `wrap'
> 2019-07-09T20:14:57.237505+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
> 2019-07-09T20:14:57.237507+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/rails.rb:42:in `call'
> 2019-07-09T20:14:57.237508+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:132:in `block (4 levels) in dispatch'
> 2019-07-09T20:14:57.237509+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:243:in `stats'
> 2019-07-09T20:14:57.237511+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:127:in `block (3 levels) in dispatch'
> 2019-07-09T20:14:57.237512+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_logger.rb:8:in `call'
> 2019-07-09T20:14:57.237514+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:126:in `block (2 levels) in dispatch'
> 2019-07-09T20:14:57.237515+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/job_retry.rb:73:in `global'
> 2019-07-09T20:14:57.237516+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:125:in `block in dispatch'
> 2019-07-09T20:14:57.237518+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:48:in `with_context'
> 2019-07-09T20:14:57.237520+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
> 2019-07-09T20:14:57.237521+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
> 2019-07-09T20:14:57.237522+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
> 2019-07-09T20:14:57.237526+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
> 2019-07-09T20:14:57.237527+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
> 2019-07-09T20:14:57.237529+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
> 2019-07-09T20:14:57.237530+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.5.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'

**Comment by pzupan** [comment]
sensu-aggregate-check_0.0.5.tgz has non-utf8 charachters in the readme.  "An aggregate makes it possible to treat the result of multiple disparate check executions ___ executed across multiple disparate systems ___ as a single result (Event)."  I believe the underscores are actually non-compliant characters.  The fix was to replace them with a space, which seems to generate the proper readme for the asset, but the ActiveStorage,analyze blob is still throwing an exception with for the encoding and not completing the work.
