### ISSUE TITLE
Enhancement:  Remove namespace from generated asset configs

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#185]
As of Sensu Go 5.11  sensuctl will automatically fill in the namespace if it is missing.

We should stop populating the namespace metadata attribute in the generated configs.

**Comment by talarczykco** [comment]
Older versions of sensuctl will fail with the following if the namespace metadata attribute is missing (commenting here for future searchers).

```error validating resource 0 (/api/core/v2/namespaces//assets/sensu-plugins-http_alpine_amd64): namespace cannot be empty```
