### ISSUE TITLE
Enhancement: include platform and arch in the asset name

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#186]
To prevent people from accidentally overwriting an asset resource from different platforms into their live configuration, we should extend the asset name as encoded in the metadata block to include platform and arch.

**Comment by jspaleta** [comment]
yikes!
There is a bug  in the formatting of the name.
Need to use dashes between
Currently Bad:
name: debian amd64 - sensu-plugins-memory-checks

Strawman Fix:
sensu-plugins-memory-checks_debian_amd64

**Comment by pzupan** [comment]
sensu-plugins-memory-checks_debian_amd64 format is deployed to staging now

**Comment by jspaleta** [comment]
I just pulled:
https://bonsai-asset-index-staging.herokuapp.com/assets/jspaleta/sensu-plugins-http/versions/5.2.0-jef.1
For centos amd64... sensuctl create -f installed it.

**Comment by jspaleta** [comment]
i added tags in staging as well,   the tags annotation looks good too.
