### ISSUE TITLE
Enhancement:  Increase prominance of Tier status and support implications

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#191]
Definitely needs discussion, but there is a need to make it more obvious what the tiers imply in terms of support and what feedback channels are most appropriate for that tier.

Possible Changes:
Restructure front page to lift tier explanation "above the fold" some how. 

Add a feedback mechanism on each asset..
Community tier would point into github issues
Supported tier would point into github issues
Enterprise tier would point to Sensu Inc. support url for Enterprise customers.

**Comment by jspaleta** [comment]
whatever the support url is, it needs to be driven into the generated configs as an annotation as well most likely.

**Comment by mbiang** [comment]
Let's make the following changes to the Asset page:

- On the tier name, create a hover effect that states the description of the tier.  The descriptions are available on the homepage.
- On the sidebar, we should add a "Report an Issue"  link below the "Stats" section.
- Enterprise tier assets should link to:  https://account.sensu.io
- Github assets should link to the Github repository.
- Github assets should be able to have their Report an Issue link overridden by a setting in the bonsai.yml.
