### ISSUE TITLE
Improve Bonsai search function 

### ISSUE THREAD

**Issue by calebhailey** [sensu/bonsai-asset-index#194]
Example: searching for "monitoring-plugins" in Bonsai don't yield any results: 

https://bonsai.sensu.io/assets?utf8=%E2%9C%93&supported_platform_id=&q=monitoring-plugins

But this exists: https://bonsai.sensu.io/assets/calebhailey/sensu-assets-monitoring-plugins

@pzupan shared this in Slack: 

> I think the issue is the dash.  Elastic search seems to index ignoring the dash.  If you search on monitoring or plugin, you'll see what I mean.  We should create a ticket for this if it needs to be fixed.  I'm sure elasticsearch can be configured to account for it.  But it may cause other problems as we also need to index by each word between the dashes.  We'll just have to see if it can be done.

Opening a ticket for posterity. :)

**Comment by mbiang** [comment]
Note that "monitoring\-plugins" brings back an exact match on the title.

**Comment by pzupan** [comment]
Pull Request #196
