### ISSUE TITLE
Add Collaborator Event to Github Repository Webhooks

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#195]
We want to automatically update the collaborator list in Bonsai whenever a collaborator is added to a tracked Github repository.

When we register the webhook for an asset in it's Github repository, we should include the "member" event.   This will allow us to receive webhook notifications when the collaborator list is modified.

See full list of webhook events:
https://developer.github.com/webhooks/

Additionally, we should limit the type of incoming events that can trigger a recompile.   We should track watch, member, and release.

Additionally, if the incoming event  is "watch" or "member", we should not recompile releases.  This should only happen on a "release" event.

**Comment by pzupan** [comment]
Pull Request #196
