### ISSUE TITLE
Asset flagging spam

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai-asset-index#197]
I noticed a couple of days ago that there was an asset <https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-rabbitmq> that was flagged:

<img width="851" alt="Screen Shot 2019-08-09 at 10 58 04 AM" src="https://user-images.githubusercontent.com/898627/62799534-12dc9580-baaf-11e9-8230-53ff834b35b5.png">

However, the reason reported for it being flagged was spam. Ideally, the ability to report an asset would IMO 1.) not be scoped to allow for anonymous reports and 2.) implement a captcha. The last thing I'd want to see have happen is for us to get a bunch of spam about plugins, or see this feature used maliciously.

**Comment by mbiang** [comment]
I think the best way to solve this would be to require that the user be logged in to be able to report an asset as spam.  If the user is not signed in, the Flag Asset link should open a dialog saying "You have to sign in to flag as asset.  [Button]Sign In With Github[Button]".
