### ISSUE TITLE
Add new API endpoint for "multi-build" assets 

### ISSUE THREAD

**Issue by calebhailey** [sensu/bonsai-asset-index#204]
Related to: https://github.com/sensu/sensu-go/issues/3067 

Add a new API endpoint for generating "multi-build" asset definitions: 

```
/api/v1/assets/:username/:id/:version/release_asset
```

This should work similar to the existing API endpoint, but without requiring `platform` and `arch` route segments: 

```
/api/v1/assets/:username/:id/:version/:platform/:arch/release_asset
```

The output should look like this: 

```json
{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "labels": {},
    "annotations": {
      "sensu.io.bonsai.url": "https://bonsai.sensu.io/sensu/sensu-slack-handler",
      "sensu.io.bonsai.api_url": "https://bonsai.sensu.io/api/v1/assets/sensu/sensu-slack-handler/",
      "sensu.io.bonsai.tier": "Supported",
      "sensu.io.bonsai.version": "1.0.3",
      "sensu.io.bonsai.tags": null
    }
  },
  "spec": {
    "builds": [
      {
        "url": "xxx",
        "sha512": "xxx", 
        "filters": [
          "entity.system.os == 'linux'",
          "entity.system.arch == 'amd64'",
          "entity.system.platform_family == 'centos'"
        ],
        "headers": {
          "Authorization": "Bearer $TOKEN",
          "X-Forwarded-For": "client1, proxy1, proxy2"
        }
      },
      {
        "url": "xxx",
        "sha512": "xxx", 
        "filters": [
          "entity.system.os == 'linux'",
          "entity.system.arch == 'amd64'"
        ],
        "headers": {
          "Authorization": "Bearer $TOKEN",
          "X-Forwarded-For": "client1, proxy1, proxy2"
        }
      }
    ]
  }
}
```

**Comment by portertech** [comment]
@calebhailey @amdprophet if an asset bonsai yml does not yet include `builds`, perhaps we should populate a single build using the top level core/v2 url, sha512, and filters.

**Comment by jspaleta** [comment]
FYI the headers section might be something bonsai may not support currently in the .bonsai.yml.

I think it might be out of scope for now, as this is only really use for private assets not served from bonsai

**Comment by jspaleta** [comment]
Note on the web-ui:  For a period of time we'll need to have a way to choose between multi-build and individual arch yaml.  Not sure how to do that exactly.

**Comment by jspaleta** [comment]
Note:
annotations format needs to be updated in existing endpoint to match this:

**Comment by mbiang** [comment]
Note - we are making two changes to the asset Annotations.

- sensio.io.bonsai.url should point to the asset URL on bonsai, not the binary. 
 https://bonsai.sensu.io/api/v1/assets/sensu/sensu-slack-handler/
- sensu.io.bonsai.api_url should point to the api URL for the asset. For example: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-slack-handler/

**Comment by jspaleta** [comment]
reverse namespace:
io.sensu.bonsai.api_url  
io.sensu.bonsai.url

**Comment by mbiang** [comment]
Note reversing namespace should apply to all configs, both from the API and Web UI
