### ISSUE TITLE
Enhancement: Advanced Search UI -> platform search

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#206]
Because platform strings as understood by bonsai can be anything at present, listing the platforms individually will become unwieldy in the UI. 

Two possible ideas:
1) limit the search to a specific set of platforms and treat them as substrings to case insensitive match in the platform field:
Any Linux Centos Debian Windows Alpine OsX

2) provide a scrollable list of all platforms and allow multi-selection and treat as exact match.

**Comment by mbiang** [comment]
We are leaning toward option 1.  In addition to the predefined list of platforms, let's add an "Other" field that allows users to enter any other search string.
