### ISSUE TITLE
Enhancement: require github semver 1.0 or 2.0 release tags

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#210]
Need to start locking down what bonsai considers viable asset release tags from github to ensure well behaved asset lifecycle logic.

**Goal:**
make sure bonsai only exposes SemVer 2.0 tags in its API and web UI, but allow Bonsai to ingest both SemVer 2.0 and SemVer 1.0 tags from github.

**Context:**
Starting to put together the asset life cycle management story. Need to have bonsai annotated versions conform to semver to make it possible to calculate if "newer" asset is available.

**Strawman Proposal:**
* When Bonsai compiles list of releases from github, check for semver 1.0 or 2.0 compliance. Hide any release from UI and API asset listing that does not comply with semver tagging requirements.

* Allow semver 2.0 compliant github tagging with optional 'v' or 'V' prefix

* When outputting version information in API and web UI and config file annotations. strip the 'v' prefix and just show the semver 2.0 version form X.Y.Z without the 'v' prefix.

* If both vX.Y.Z tag and X.Y.Z tagged releases exist in github, prefer to compile the vX.Y.Z release tag.

**Potential problems:**
Because we are effectively collapsing vX.Y.Z and X.Y.Z github tag into the same space, there's potential here for a mistake.  Strawman proposal tries to address this by prefering vX.Y.Z release tag if both exist in github.

**Comment by pzupan** [comment]
The compilation process already rejects any release that does not comply with semver 2.
