### ISSUE TITLE
Bug: Multi-build config should not have header attributes

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#221]
the multi-build api endpoint is producing json that is include the headers attribute for each build.
This should not be included by default in our public community bonsai. 

This might be a ruby or rails internal variable associated with the http session leaking into the config being generated.

here's an example of what I'm seeing being populated right now for a build using the API endpoint  `https://bonsai.sensu.io//api/v1/assets/<user>/<asset>/<version>/release_asset_builds`
```
      {
        "url": "blah blah blah",
        "sha512": "something",
        "filters": [
          "entity.system.os == 'linux'",
          "entity.system.arch == 'amd64'"
        ],
        "headers": {
          "Authorization": "Bearer $TOKEN",
          "X-Forwarded-For": "$CLIENT"
        }
      },
```
The "headers" attribute shouldn't be there by default.

I would say that unless explicitly defined in the .bonsai.yml, headers should be hidden.

**Comment by mbiang** [comment]
Thanks @jspaleta - I've removed these, and deployed a hotfix with this patch.   Thanks!
