### ISSUE TITLE
Search bar doesn't extend past 1400px

### ISSUE THREAD

**Issue by apaskulin** [sensu/bonsai-asset-index#65]
### Current behavior

![screen shot 2019-01-15 at 11 13 03 am](https://user-images.githubusercontent.com/11339965/51203735-a69e0880-18b6-11e9-90fc-9dc2cb094213.png)

The search bar stops expanding at 1400px

### Expected behavior

The search bar should extend to fill the width of the screen.

**Comment by pzupan** [comment]
Fixed 2d0dca7d8c2580ebd031b71ad9f9ef23f2784a05
