### ISSUE TITLE
Github Release missing release assets

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#69]
Some release assets are missing on Github based assets.

**Expected Behavior**
The [sensu-pushbullet-handler](https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler) has several release assets defined in the Github repository for [Release 0.0.4](https://github.com/rgeniesse/sensu-pushbullet-handler/releases/tag/0.0.4).  After adding this asset to Bonsai, I expected to see these release assets listed in the sidebar of the [Extension Page](https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler/versions/0.0.4) for version 0.0.4.   

Additionally, I expect to be able to use the "Recompile Asset" function form the "Manage Asset" menu as the asset owner or site admin.

**Current Behavior**
- No release assets show after adding the asset to the Bonsai index (they weren't found when initially scanning the Github repository).
- The "Recompile Asset" feature doesn't pull in the release assets either.

**Comment by rgeniesse** [comment]
Here's the original issue with the [bonsai.yml](https://github.com/rgeniesse/sensu-pushbullet-handler/blob/fef31acfa59ade40ba9c25b9f355766e019aaab0/.bonsai.yml#L58) file as I have fixed it in master, so the above comment's link is no longer valid in showing the issue.

**Comment by mbiang** [comment]
We are now showing asset compilation errors as part of #81, and now the [sensu-pushbullet-handler](https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler) asset indicates that the [bonsai.yml](https://github.com/rgeniesse/sensu-pushbullet-handler/blob/master/.bonsai.yml) file in version 0.0.6 is malformed, particular the 8th build section.   When inspecting the bonsai.yml however, I only see seven build entries, so I'm not sure exactly what's wrong.    We will continue to investigate.

**Comment by mbiang** [comment]
@rgeniesse - Ahh, the issue I mentioned in my last [comment](https://github.com/sensu/bonsai-asset-index/issues/69#issuecomment-459132527) has to do with the bad indentation in the bonsai.yml file.  I didn't realize release 0.0.6 was issues prior to you making that change.

Regarding the master branch, I believe it won't show any release assets (since it's not a release and there's no way to attach binaries to master). @demillir does that sound right to you?

@rgeniesse - you could try cutting another release, and I your release assets should now show up, or you should see a syntax error message.

**Comment by rgeniesse** [comment]
@mbiang I've cut a new release and things look much better. This release includes the fix to the bonsai.yml file.

Getting an error about a compilation error for a windows build, CI shows it built so not sure what to make of that:

<img width="843" alt="screen shot 2019-01-30 at 8 32 53 pm" src="https://user-images.githubusercontent.com/19964713/52030854-8da87080-24ce-11e9-8036-c2142afb92fd.png">

I did have to re-compile after to get the rest of the rest of the release assets to show up, but I may also have been too impatient.

**Comment by mbiang** [comment]
@rgeniesse - we are looking into this - I noted that releases 1.0.0 and 1.0.1 are also missing assets:

https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler/versions/1.0.1
https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler/versions/1.0.0
https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler/versions/0.0.7

cc: @pzupan

**Comment by pzupan** [comment]
Pull request #97
