### ISSUE TITLE
Adding asset doesn't update release drop down, readme or downloads section properly

### ISSUE THREAD

**Issue by rgeniesse** [sensu/bonsai-asset-index#72]
**Expected behavior**

Adding an asset shows readme, download links and all versions in releases drop down.

**Current behavior**

I've added a handler asset here:

https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler

But it seems to not want to update the releases drop down, the readme or add the download packages with their checksums to the lower right hand section. At somepoint something shook lose a bit as initially no releases were showing, now 0.0.4 and 0.0.5 are. Recompile releases seems to have no immediate effect or even in the following hours.

This should have 0.0.6 as well:

<img width="737" alt="screen shot 2019-01-22 at 12 01 39 pm" src="https://user-images.githubusercontent.com/19964713/51562031-9e594680-1e3d-11e9-9433-cbc2f9577ca1.png">

<img width="1050" alt="screen shot 2019-01-22 at 12 03 01 pm" src="https://user-images.githubusercontent.com/19964713/51562056-b29d4380-1e3d-11e9-9484-7c7441570000.png">

And the downloads section isn't populating properly:

<img width="476" alt="screen shot 2019-01-22 at 12 01 43 pm" src="https://user-images.githubusercontent.com/19964713/51562202-217a9c80-1e3e-11e9-834b-8f20a6021132.png">

And then the readme you'll see is missing based on the asset link above.

Other assets that were added near or after mine appear to be working:

https://bonsai.sensu.io/assets/cwjohnston/sensu-pushover-handler
https://bonsai.sensu.io/assets/sensu/sensu-prometheus-collector

I've done a configuration comparison with .bonsai.yml to these other two repos and don't see any differences outside of single quoted values. Also done a few new releases after adding the asset to bonsai and that doesn't seem to do anything.

**Comment by mbiang** [comment]
We think this may be related to #73 and #69.

**Comment by rgeniesse** [comment]
Thanks @mbiang. I _thought_ I fixed that spacing error, but obviously did not (or it didn't end up in master somehow). I've updated it and re-ran the recompile releases action. The readme is now showing up. I don't know if that action will make the asset links appear, though. That may be a thing that happens on the CI side.

**Comment by rgeniesse** [comment]
fwiw, the readme is working for the pushbullet handler after recompiling the release, but at some point after it disappears.

**Comment by mbiang** [comment]
@rgeniesse - this issue should now be resolved by #97.  I'm going to close this.  Please re-open if you encounter this issue again.
