### ISSUE TITLE
Sidekiq is viewable by non-admins

### ISSUE THREAD

**Issue by demillir** [sensu/bonsai-asset-index#88]
The Sidekiq dashboard at https://bonsai.sensu.io/sidekiq is visible to non-admin users and non-logged in visitors.

This ticket will be resolved when:

- [ ] only admin users can view the Sidekiq dashboard page

**Comment by demillir** [comment]
Here is some relevant info on adding authorization to the `/sidekiq` path:
https://github.com/mperham/sidekiq/wiki/Monitoring#authentication

**Comment by pzupan** [comment]
Pull request #98
