### ISSUE TITLE
Asset tiers should be viewable as a category

### ISSUE THREAD

**Issue by cwjohnston** [sensu/bonsai-asset-index#91]
## Expected behavior

As a user of the site I can browse assets by tier.

## Current behavior

Assets are not grouped by tier, can only be searched by tier if the tier is also a tag.

## Possible solution

Make tiers an organizing identifier similar to but distinct from tags

Make the tier badge(?) on an asset page clickable, linking to a view of all the assets in that tier

![2019-02-05 at 11 00 am](https://user-images.githubusercontent.com/148017/52304967-346a9200-2951-11e9-882f-b0935b5058c0.png)

**Comment by pzupan** [comment]
Pull request #94
