### ISSUE TITLE
Badges don't render properly

### ISSUE THREAD

**Issue by asachs01** [sensu/bonsai-asset-index#96]
Page: https://bonsai.sensu.io/assets/rgeniesse/sensu-pushbullet-handler
Screenshot:
![screenshot from 2019-02-07 16-18-42](https://user-images.githubusercontent.com/898627/52443592-1f7a3400-2af4-11e9-8da0-9bbac63ef23e.png)

Image source link:  `https://github.com/rgeniesse/sensu-pushbullet-handler/raw/1.0.1///travis-ci.com/rgeniesse/sensu-pushbullet-handler.svg?branch=master`

Issue:
Badges aren't being rendered due to the github page for the asset being appended to the badge.

Solution: 
Remove the github page portion of the link and badges work again.

**Comment by pzupan** [comment]
pull request #99
